[build]
  publish = "public/"
  command = "cd functions && npm i"

[functions]
  directory = "functions/"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
