[build]
  publish = "public/"
  command = "cd functions && npm i"

[functions]
  directory = "functions/"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  from = "/hello-world"
  to = "https://gdsc.community.dev/j/aq9vjsnk9hb9d/"
  status = 302
  
[[redirects]]
  from = "/30daysofcloud"
  to = "https://gdsc.community.dev/e/m8vjnf/"
  status = 302

[[redirects]]
  from = "/cybersec101"
  to = "https://gdsc.community.dev/events/details/developer-student-clubs-amrita-school-of-engineering-coimbatore-presents-cybersecurity-101-a-hands-on-session/"
  status = 302
