[build]
  publish = "public/"
  command = "cd functions && npm i"

[functions]
  directory = "functions/"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  from = "letsgitstartedone"
  to = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDhhNzQyN2ItZmI5ZS00NmJmLWExMDgtZWZiZDY3ZmJmY2Iy%40thread.v2/0?context=%7b%22Tid%22%3a%2200f9cda3-075e-44e5-aa0b-aba3add6539f%22%2c%22Oid%22%3a%22d721681b-7ad3-4b5c-b2c3-a012369e365f%22%7d"
  status = 302
